region: us
version: '2'
authtoken: 2idcq5RCgwCkpZpSTiHKxX7RV41_5Sux1mFFCUmgCihBVfab6
tunnels:
  twilio-app:
    addr: 8001
    proto: http
  plivo-app:
    addr: 8002
    proto: http
  bolna-app:
    addr: 5001
    proto: http
